name = "blog"
main = "build/worker/shim.mjs"
compatibility_date = "2023-03-22"
routes = [
    { pattern = "blog.imipy.com/*", zone_id = "c4466b12cd602c698035cb8509e464db" },
]
usage_model = "bundled"
[build]
command = "cargo install -q worker-build && worker-build --release"

[vars]
MY_DOMAIN = "blog.imipy.com"
NOTION_DOMAIN = "ac0d3r.notion.site"
PAGE_MAP = '{"/":"4b2780d3bf864ab3bee6044612f6e631","/links":"5aec357c2b3b4297840c388055644954","/donate":"7e284265437a49249728e75aea5564bf","/about":"0d05dcdc061e43ed9417db8b3af2d5ce"}'
COMMENT_MAP = '{"data-repo":"ac0d3r/notion-blog","data-repo-id":"R_kgDOI-Cshw","data-category-id":"DIC_kwDOI-Csh84CZeRn","data-mapping":"title","data-input-position":"top","data-theme":"preferred_color_scheme","data-lang":"zh-CN"}'
PAGE_TITLE = "巴斯.zznQ"
PAGE_DESCRIPTION = "巴斯.zznQ's Blog"
ICON_URL = "https://avatars.githubusercontent.com/u/26270009?v=4"
QUERY_BODY = '{"source":{"type":"collection","id":"f9a4e291-ff5e-4a7d-938e-a6c132645b5e","spaceId":"8413365a-93b4-4477-ba09-8ed90e6c05cc"},"collectionView":{"id":"0a498990-5643-42f0-b2d1-07dffcdb1b9f","spaceId":"8413365a-93b4-4477-ba09-8ed90e6c05cc"},"loader":{"type":"reducer","reducers":{"collection_group_results":{"type":"results","limit":50},"table:uncategorized:title:count":{"type":"aggregation","aggregation":{"property":"title","aggregator":"count"}}},"sort":[{"property":"Px~q","direction":"descending"}],"searchQuery":"","userTimeZone":"Asia/Shanghai"}}'

[placement]
mode = "smart"
